name: Cleanup GHCR
on:
  workflow_run:
    workflows: ["Build Rust Webhook"]
    types:
      - completed
  
jobs:
  delete-versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'graft-hook'
          package-type: 'container'
          min-versions-to-keep: 3 # Keeps the 5 most recent builds
          delete-only-untagged-versions: true # Deletes images that no longer have a tag (like "latest")